# Generated by Django 4.0.6 on 2022-08-03 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_cards_owner_shoppingcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcar',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
