# Generated by Django 4.0.6 on 2022-08-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_shoppingcar_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcar',
            name='cardlist',
            field=models.ManyToManyField(blank=True, to='API.cards'),
        ),
    ]
